namespace Resume.Abstraction.Enums.Keys;

public enum CourseKey
{
    ORACLE_JAVA_SE_8_PROGRAMMING_NAME,
    ORACLE_JAVA_SE_8_PROGRAMMING_DESCRIPTION,

    SPECIALISTERNE_ACADEMY_NAME,
    SPECIALISTERNE_ACADEMY_DESCRIPTION,
}
