namespace Resume.Abstraction.Enums.Keys;

public enum EmploymentKey
{
    UNKNOWN = 0,
    EMPLOYER_APPS4ALL,
    EMPLOYER_TV2,
    EMPLOYER_FASHIONHERO_INTERNSHIP,
    EMPLOYER_NOERGAARD_MIKKELSEN_INTERNSHIP,
    EMPLOYER_ODENSE_MOBIL_REP,
    JOB_TITLE_APPS4ALL,
    JOB_TITLE_TV2,
    JOB_TITLE_FASHIONHERO_INTERNSHIP,
    JOB_TITLE_NOERGAARD_MIKKELSEN_INTERNSHIP,
    JOB_TITLE_ODENSE_MOBIL_REP,
    WORK_DESCRIPTION_APPS4ALL,
    WORK_DESCRIPTION_TV2,
    WORK_DESCRIPTION_FASHIONHERO_INTERNSHIP,
    WORK_DESCRIPTION_NOERGAARD_MIKKELSEN_INTERNSHIP,
    WORK_DESCRIPTION_ODENSE_MOBIL_REP,
    EMPLOYMENT_TYPE_CONTRACT,
    EMPLOYMENT_TYPE_INTERNSHIP,
    EMPLOYMENT_TYPE_PERMANENT,
    EMPLOYMENT_TYPE_FREELANCE,
    EMPLOYER_FLOWPOINT_DEFENCE,
    JOB_TITLE_FLOWPOINT_DEFENCE,
    WORK_DESCRIPTION_FLOWPOINT_DEFENCE,
}
