namespace Resume.Abstraction.Enums.Keys;

public enum LinkKey
{
    UNKNOWN = 0,
    FASHION_HERO_GITHUB_PROJECT,
    TV2_CLIPTOOL_GITHUB_PROJECT,
    REMARK_GITHUB,
    REMARK_LINKEDIN,
    REMARK_PERSONAL_PAGE,
    TITLE_GITHUB,
    TITLE_LINKEDIN,
    TITLE_PERSONAL_PAGE,
    PERSONAL_GITHUB,
    NOERGAARD_MIKKELSEN_GITHUB_PROJECT,
    PERSONAL_LINKEDIN,
    PERSONAL_PAGE,
    TRACKER_GITHUB_PROJECT,
    RETOLD_MODS_GITHUB_PROJECT,
    RETOLD_DEV_TOOL_PROJECT,
    RETOLD_MOD_MANAGER_GITHUB_PROJECT,
    PROTECT_THE_TEMPLE_GITHUB_PROJECT
}
