namespace Resume.Abstraction.Enums.Keys;

public enum UserInterfaceKey
{
    UNKNOWN = 0,
    TITLE,
    SKILLS_HEADER,
    EMPLOYMENT_HEADER,
    EDUCATION_HEADER,
    REFERENCES_HEADER,
    PHONE_LABEL,
    LINKS_HEADER,
    LANGUAGES_HEADER,
    PROFILE_HEADER,
    NAME_LABEL,
    EMAIL_LABEL,
    ADDRESS_LABEL,
    DATE_OF_BIRTH_LABEL,
    GENERAL_HEADER,
    THE_LABEL,
    OF_LABEL,
    PROJECTS_HEADER
}
